export const appActionTypes = {
  DELETE_USER: "DELETE_USER",
  ADD_USER: "ADD_USER",
  DELETE_TASK: "DELETE_TASK",
  DONE_TASK: "DONE_TASK",
  ADD_TASK: "ADD_TASK",
  SET_FILTER: "SET_FILTER",
  SET_SEARCH: "SET_SEARCH",
  FILTER_LIST: "FILTER_LIST",
};
